# Generated by Django 3.0.3 on 2020-02-14 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='product',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.Product'),
        ),
        migrations.AddField(
            model_name='product',
            name='prices',
            field=models.ManyToManyField(related_name='prices', to='orders.Price'),
        ),
    ]
