# Generated by Django 3.0.3 on 2020-02-14 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20200214_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prices',
            field=models.ManyToManyField(blank=True, related_name='prices', to='orders.Price'),
        ),
    ]
